FROM clojure:latest
COPY . /app
WORKDIR /app
CMD ["lein", "run"]

# commands to generate a closure app in the docker file then copy to local file system
# CMD ["lein", "new", "app", "clojure_noob"]
# docker cp braveclojure_app_1:/app ./
